-- Server-side application submission error log.
-- Privacy rule: do NOT store student name, phone number, email, notes, or free-text answers here.

create table if not exists public.submission_error_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id text not null,
  status_code integer not null check (status_code between 400 and 599),
  error_type text not null,
  error_message text not null,
  region text,
  plan text,
  matching_type text,
  teacher_id text,
  teacher_name text,
  upstream_status integer,
  upstream_code text,
  environment text
);

create index if not exists submission_error_logs_created_at_idx
  on public.submission_error_logs (created_at desc);

create index if not exists submission_error_logs_error_type_idx
  on public.submission_error_logs (error_type, created_at desc);

create index if not exists submission_error_logs_status_code_idx
  on public.submission_error_logs (status_code, created_at desc);

alter table public.submission_error_logs enable row level security;

-- The browser/public key must never be able to read or write these logs.
revoke all on table public.submission_error_logs from anon, authenticated;

-- Supabase backend secret keys act with service-role privileges.
grant select, insert, update, delete on table public.submission_error_logs to service_role;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'submission_error_logs_id_seq'
  ) then
    grant usage, select on sequence public.submission_error_logs_id_seq to service_role;
  end if;
end $$;

comment on table public.submission_error_logs is
  'Server-only NADO application submission errors. No student PII or free-text answers.';
